name: Publish

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/CHANGELOG.md"
      - "**/README.md"

defaults:
  run:
    shell: pwsh

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-publish:
    if: github.actor != 'github-actions[bot]' # Exclude commits made by GitHub Actions bot
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for Update_Changelog_Direct to push to main
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Required for GitVersion

      - name: Install GitVersion
        uses: GitTools/actions/gitversion/setup@v4.5.0
        with:
          versionSpec: "5.x"

      - name: chmod build.ps1
        run: chmod +x build.ps1

      - name: Package Module
        run: |
          ./build.ps1 -ResolveDependency -Task pack

      - name: Publish Module
        env:
          GalleryApiToken: ${{ secrets.PSGALLERY_API_KEY }}
          GitHubToken: ${{ github.token }}
        run: |
          ./build.ps1 -ResolveDependency -Task publish
